/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Growl
 #	author : miyako
 #	2016/07/22
 #
 # --------------------------------------------------------------------------------*/

#import <Growl/Growl.h>
#include <mutex>

// --- Growl
void Growl_Set_notification_method(sLONG_PTR *pResult, PackagePtr pParams);
void Growl_SET_MIST_ENABLED(sLONG_PTR *pResult, PackagePtr pParams);
void Growl_Get_mist_enabled(sLONG_PTR *pResult, PackagePtr pParams);
void Growl_POST_NOTIFICATION(sLONG_PTR *pResult, PackagePtr pParams);
void Growl_Get_notification_method(sLONG_PTR *pResult, PackagePtr pParams);

void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

//internal variable

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

//enum
typedef enum
{
	NotificationWasClicked = 0,
	NotificationTimedOut = 1
} notification_type_t;
